version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./generateDatabase.sql:/docker-entrypoint-initdb.d/generateDatabase.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    entrypoint: ["/docker-entrypoint-initdb.d/init-db.sh"]

volumes:
  postgres_data:
    driver: local
